
table usuario{
  id int [primary key]
  nombre varchar(300)
  apellido varchar (300)
  correo_electronico varchar (300)
  contrasenia varchar(300)
  fecha_registro datetime
  salario_mensual_base decimal(18,2)
  estado_usuario bit

  creado_por int
  modificado_por int
  creado_en DATETIME
  modificado_en DATETIME
}

table presupuesto{
  id int [primary key]
  usuario_propietario varchar (300)
  nombre_descriptivo varchar (300)
  descripcion varchar (300)
  anio_inicio smallint
  mes_inicio tinyint
  anio_fin smallint
  mes_fin tinyint
  total_ingreso decimal(18,2)
  total_gasto decimal(18,2)
  total_ahorro decimal(18,2)
  fecha_hora_creacion datetime
  estado_presupuesto bit //activo/cerrado/borrador

  creado_por int
  modificado_por int
  creado_en DATETIME
  modificado_en DATETIME

}

table categorias{
  id_categorias int [primary key]
  nombre varchar (300)
  descripcion varchar (600)
  tipo_categoria varchar (300) //(ingreso/gasto/ahorro)

  creado_por int
  modificado_por int
  creado_en DATETIME
  modificado_en DATETIME
}

table subcategorias{
  id_subcategorias int [primary key]
  id_categorias int
  nombre varchar (300)
  descripcion varchar (600)
  es_activo bit
  subcategoria_por_defecto bit

  creado_por int
  modificado_por int
  creado_en DATETIME
  modificado_en DATETIME
}

table presupuesto_detalle{
  id int [primary key]
  id_presupuesto int
  id_subcategorias int
  monto_mensual decimal(18,2)
  observacion_monto varchar (300)

  creado_por int
  modificado_por int
  creado_en DATETIME
  modificado_en DATETIME
}

table obligacion_fija{
  id int [primary key]
  id_subcategoria int
  nombre varchar (300)
  descripcion varchar (400)
  monto_fijo_mensual decimal(18,2)
  dia_del_mes tinyint 
  esta_vigente bit
  fecha_inicio date
  fecha_finalizacion date

  creado_por int
  modificado_por int
  creado_en DATETIME
  modificado_en DATETIME
}

table transaccion { 
  id_transaccion int [primary key]
  id_presupuesto_detalle int
  descripcion varchar (300)
  metodo_de_pago varchar (300)
  anio_transaccion smallint
  mes_transaccion tinyint
  monto_transaccion decimal(12,2)
  tipo_transaccion varchar (300) //(efectivo/tarjeta_debito/tarjeta_credito/transferencia)
  fecha_hora_registro DATETIME
  
  creado_por int
  modificado_por int
  creado_en DATETIME
  modificado_en DATETIME
}

table obligacion_transaccion{
  id_transaccion int [primary key]
  id_obligacion int
}

Ref: "categorias"."id_categorias" < "subcategorias"."id_categorias"

Ref: "presupuesto"."id" < "presupuesto_detalle"."id_presupuesto"

Ref: "subcategorias"."id_subcategorias" < "presupuesto_detalle"."id_subcategorias"

Ref: "usuario"."id" < "presupuesto"."usuario_propietario"

Ref: "obligacion_fija"."id" < "obligacion_transaccion"."id_obligacion"

Ref: "transaccion"."id_transaccion" < "obligacion_transaccion"."id_transaccion"

Ref: "presupuesto_detalle"."id" < "transaccion"."id_presupuesto_detalle"

Ref: "subcategorias"."id_subcategorias" < "obligacion_fija"."id_subcategoria"
